import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    const startTelegramBot = async () => {
        try {
            const response = await axios.get('api/telegram');

            if (response.status === 200) {
                console.log('Telegram bot has been launched');
            } else {
                console.error('Error starting Telegram bot');
            }
        } catch (error) {
            console.error('Error starting Telegram bot', error);
        }
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <nav className={styles.nav}>
                    <Link href="add">Add project</Link>
                    <Link href="profile">Profile</Link>
                    <Link href="projects">Projects</Link>
                </nav>
                <button
                    type="button"
                    onClick={startTelegramBot}
                    className={styles.btn}
                >
                    Start telegram bot
                </button>
            </header>
            <main className={styles.main}>
                <div className={styles.center}>
                    <Image
                        className={styles.logo}
                        src="/next.svg"
                        alt="Next.js Logo"
                        width={180}
                        height={37}
                        priority
                    />
                    <div className={styles.thirteen}>
                        <Image
                            src="/thirteen.svg"
                            alt="13"
                            width={40}
                            height={31}
                            priority
                        />
                    </div>
                </div>
            </main>
        </>
    );
}
